services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    ports:
      - "5433:5432"  # <--- B-d-l-i had l-ligne 5433:5432
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: app
# ... (l-baqi khalih kifma houwa)
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "app", "-U", "app"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###